name: I AM Luigi
favicon: null
layout_spectrum: 0.92698
typography_spectrum: 0.0013851048424839973
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9634661723393947
  lightness: 0.09763720142655075
  saturation: 0.4570238427259028
  rhythmicContrast: 0.02517818403430283
purpose: []
